### ISSUE TITLE
OwinLifetimeScopeKey configurable

### ISSUE THREAD

**Issue by brockallen** [autofac/Autofac.Owin#1] opened 2015-05-12 15:14 UTC
Is there any way we can make the OwinLifetimeScopeKey configurable and/or allow for some sort of prefix?

We have a scenario where 2 different copies of Autofac are being used in the same OWIN pipeline. Given that they're using the same key for storing per-request data in the OWIN environment then we get cross-over behavior and undesirable results. Obviously the MiddlewareRegisteredKey would also be affected by this.

I can provide more contextual information if desired. Thanks.

**Comment by tillig** [comment] 2015-05-12 15:23
Is there a way to avoid doing what you're doing?

There are actually two different keys in the OWIN middleware - one key to register with the app to say, "The OWIN middleware is registered!" to avoid multiple copies of the middleware in one app; and the other to indicate the lifetime scope metadata.

That constant indicating the lifetime scope then is used in the MVC and Web API OWIN middleware to retrieve the single request lifetime scope and use it in either pipeline.

In general, I'd say running multiple copies of Autofac in the same application is... well, if not _unsupported_, at least _really fringe_. Trying to configure the key would mean you'd also have to configure the key in the other middleware components (MVC/Web API integration). I think it could get pretty confusing pretty quickly.

With ASP.NET 5 / DNX coming down unifying the whole model, trying to use multiple containers or different versions in the same app will be even more difficult, if not impossible.

**Comment by brockallen** [comment] 2015-05-12 15:26
Well, long story short -- no, I can't avoid it. I'm using autofac within my own middleware, and ilmerging all of my dependencies into my own assembly. If a host then uses my middleware and then their own copy of autofac, then this situation arises. Since i'm building middleware, I can't control what the host does.

**Comment by tillig** [comment] 2015-05-12 15:40
I don't think at this time there's a plan to enable this to happen. We always welcome pull requests, but it'll be one for each integration library; or you can fork and make your own Autofac middleware.

I'll update this to be an enhancement request, but for now... there's no out of the box way to do what you're looking to do. Perhaps not ILMerging everything together?

**Comment by brockallen** [comment] 2015-05-12 15:42
It's ok, there's a lot more context I was trying to spare you. I'll just fork and rename the constants. If it's easy enough to make it configurable then I'll send a PR. Thx.

**Comment by tillig** [comment] 2015-05-14 15:55
Clarification: When you want multiple copies of the middleware to run, does that mean you also want multiple request lifetimes - one per middleware copy? Or would it be multiple middleware instances with only one request lifetime shared between all the middleware instances?

**Comment by huysentruitw** [comment] 2015-05-14 16:19
The problem is, by embedding Autofac in a third party middleware (Autofac A), the Autofac used in the application (Autofac B) using that third party middleware will never be considered the same. This means, if Autofac A creates a `LifetimeScope`, it will never be cast-able to the `ILifetimeScope` from Autofac B. That is what the exception linked above is all about.

So, I think, that treating them separate is the only way this can work, right?

**Comment by tillig** [comment] 2015-05-14 16:51
I don't actually know (without creating a repro). I would think that binding redirects might enable something like that to work, but... thinking about it, you may be totally right - that each middleware would HAVE to use its own lifetime scope.

Thinking this through out loud, would that mean `Autofac.WebApi.Owin` would always get the lifetime scope from the external/non-merged version of Autofac?

**Comment by huysentruitw** [comment] 2015-05-14 17:03
It depends who first called to `UseAutofacMiddleware`. If the 3rd party middleware called it first, then your application will fail to get the lifetimescope because the lifetimescope of the 3rd party middleware cannot be casted to `ILifetimeScope` from the application (the types do not match). If you application was the first, then the 3rd party middleware will fail to get the lifetimescope for the same reason.

**Comment by brockallen** [comment] 2015-05-14 17:08
I want them completely isolated and ignorant of one another. 

-Brock

**Comment by tillig** [comment] 2015-05-14 17:24
Still wrapping my head around this and making sure if changes get committed that we're getting the desired outcome...

In the common use case, the changes here shouldn't have any effect. In the use case for this issue in particular, does the fix solve the problem _and_ not break other OWIN integration packages (e.g., Web API)? Or is there a need for modification in the other OWIN integration packages? I don't have the ability to test it in both scenarios.

**Comment by brockallen** [comment] 2015-05-14 21:44
These two lines are all I needed to change to get what I needed:

https://github.com/IdentityServer/IdentityServer3/commit/06ab9cf55996444c89f1aa2db61aba8646ebcf8c#diff-c66cacd3da436a96f028fa1d340ddb18R45

https://github.com/IdentityServer/IdentityServer3/commit/06ab9cf55996444c89f1aa2db61aba8646ebcf8c#diff-0b0ce173b47df5f456dfbf8f5c1a1e1dR33

So I was originally asking to have these possible as a config option on the MW, that's all. So yes, in the common case it would not affect anyone using this in the recommended approach. But if someone (such as ourselves) need to have two copies of autofac in the owin pipeline that knew nothing about one another then this fix would allow for that. Each copy would be its own DI container and have no relation to any other copies of autofac in the same OWIN pipeline.

**Comment by tillig** [comment] 2015-05-14 22:24
I get that; what I'm not sure about without someone testing is: If we provide some sort of solution to that (e.g., enabling it to be configured or otherwise dynamic) **does it affect the Web API or MVC OWIN integration in any way?**

Looking at the Web API OWIN code, for example, [it uses `context.GetAutofacLifetimeScope()`](https://github.com/autofac/Autofac.WebApi.Owin/blob/master/src/Autofac.Integration.WebApi.Owin/DependencyScopeHandler.cs#L24) which makes use of the extension in the OWIN integration - which relies on that `Constants.OwinLifetimeScopeKey` that changed.

Does the issue "resolve itself" given the only thing that can bind to the ILMerged version of Autofac.Owin is the stuff also in the ILMerged assembly? Or is that true? Is it "first in wins?"

I don't mean to belabor the issue, it's just that we need to be sure of the behavior so we can document it and give folks an idea of what to expect and I don't have the ability at the moment to set up a repro and test the various conditions.

**Comment by huysentruitw** [comment] 2015-05-15 06:48
I understand your concern. Take Web API integration for example: I think the problem is not the `GetAutofacLifetimeScope` because the correct extension method will be chosen there. But the problem might be [`request.Properties[HttpPropertyKeys.DependencyScope] = dependencyScope;`](https://github.com/autofac/Autofac.WebApi.Owin/blob/master/src/Autofac.Integration.WebApi.Owin/DependencyScopeHandler.cs#L28) because the last Web API integration will override the property.

Alas only one `DependencyScope` can exist per OWIN pipeline and I guess this will be the same for the MVC integration because of [`httpContext.Items[typeof(ILifetimeScope)] = lifetimeScope;`](https://github.com/autofac/Autofac.Mvc.Owin/blob/master/src/Autofac.Integration.Mvc.Owin/AutofacMvcAppBuilderExtensions.cs#L60)

**Comment by huysentruitw** [comment] 2015-05-15 10:41
I've setup a self-host project containing WebAPI and ThinkTecture.IdentityServer3 v1.6.1 and added a hook to beginning of OWIN pipeline, so I could inspect the context of the incoming requests (before `await next()`) and the return context (after `await.next()`):

```C#
app.Use(async (context, next) =>
{
    await next();
});
```

I've concluded that, as long as you keep the `UseAutofacMiddleware`, `UseAutofacWebApi` and `UseWebApi` functions together, there is no problem because the required properties are overridden at the right time:

![owin request pipeline](https://cloud.githubusercontent.com/assets/4618744/7651256/b657dcda-fafe-11e4-8f17-1d09e5a61094.png)

It should even work when we keep the `OwinLifetimeScopeKey` the same (so without appending a GUID). I think the only real problem is this line: https://github.com/autofac/Autofac.Owin/blob/master/src/Autofac.Integration.Owin/AutofacAppBuilderExtensions.cs#L58

But I tried to setup a solution with 2 projects, each using different Autofac libraries but I failed miserably :)

**Comment by tillig** [comment] 2015-05-27 15:21
OK, PR #2 was merged and published to the Autofac MyGet feed at https://www.myget.org/F/autofac/ as version 3.1.1-CI-216.

Can you test it out and make sure it works as expected? If it does, I can push to NuGet as official 3.1.1.

**Comment by brockallen** [comment] 2015-06-05 03:16
I've been traveling -- I'll try to get to this on the weekend or next week. Thx

**Comment by tillig** [comment] 2015-06-15 14:06
@brockallen Just wanted to follow up on this to see if you had a chance to test it. If it's good, I'll push to NuGet.

**Comment by huysentruitw** [comment] 2015-06-15 15:07
I would not push this because it still doesn't fix it all, see https://github.com/autofac/Autofac.Owin/pull/2#issuecomment-108780348

**Comment by tillig** [comment] 2015-06-15 15:11
Hmmm. Open to suggestions. :persevere:

**Comment by huysentruitw** [comment] 2015-06-15 17:35
I just removing the `AutofacMiddelwareRegistered`-check and did some tests.

My tests show that you can hook up as many Autofac middlewares (with that check removed) as you want (talking about WebAPI only here), as long as everything is added in the right sequence (`UseAutofacMiddleware`, `UseAutofacWebApi`, `UseWebApi`, `UseAutofacMiddleware`, `UseAutofacWebApi`, `UseWebApi`, etc) to the OWIN pipeline, the `autofac:OwinLifetimeScope` gets overridden at the correct time (right before it is consumed by the `UseWebApi` middleware) and it just works.

I already asked @alexmg why he added that check here: https://github.com/autofac/Autofac.Owin/commit/6e12426152c8925a6b8a435d826dc5af38b960dc#commitcomment-11520276

So, removing that check can only break software written after 14 april 2014 and that register the middleware more than once by accident.

**Comment by brockallen** [comment] 2015-06-15 19:37
Sorry for dragging my feet on this. We did run into another issue related to our use of autofac, but given our fork I was able to work around it. I'll follow up next week when I return home from travel. 

-Brock

**Comment by tillig** [comment] 2015-09-18 19:39
@brockallen Did you try this out?

We're working on getting the DNX support out and everything's revving to version 4.0.0 so this would be a good time to add stuff like this. I can remove that defensive check at https://github.com/autofac/Autofac.Owin/commit/6e12426152c8925a6b8a435d826dc5af38b960dc#commitcomment-11520276 if that will help. I can then issue a 4.0.0-beta for testing.

**Comment by brockallen** [comment] 2015-09-18 21:05
Unfortunately no -- I certainly meant to make time. My failure.

Related to this is this issue in ASP.NET 5 which suggest that we do need to be able to configure different branches in the pipeline with different DI: https://github.com/aspnet/Home/issues/242

**Comment by tillig** [comment] 2015-09-18 22:00
Check out Autofac.Owin 4.0.0-CI-221 on the MyGet (https://www.myget.org/F/autofac/) and let me know what you think. It includes PR #3 as well, which allows separating the registration of the Autofac lifetime scope injection from middleware registered with Autofac.

I'm having a tough time keeping up on all the changes and requirements for DNX and ASP.NET 5, so suggestions/pointers are welcome. I spend a good lot of time just trying to keep the build stable from beta to beta... plus the other integration libraries that need to be updated for compatibility. (PRs welcome! :smile:)

**Comment by brockallen** [comment] 2015-09-18 22:44
np -- thanks and i'll see if it can help us.

**Comment by tillig** [comment] 2015-09-21 15:32
I've pushed a version to NuGet - [4.0.0-beta7-222](https://www.nuget.org/packages/Autofac.Owin/4.0.0-beta7-222) - that contains the latest changes including PR #3.

**Comment by tillig** [comment] 2015-11-04 14:53
Just wanted to follow up here and see if this helped. Given it may tie into [Identity Server issue #2117](https://github.com/IdentityServer/IdentityServer3/issues/2117) I thought I'd add the reference and see if there was anything left to do here.

If not, I'll close it up and call it good.

**Comment by brockallen** [comment] 2015-11-04 15:04
I don't think it's related.

This issue here was essentially that we needed to have an isolated sub-container unrelated to any other code running in the OWIN pipeline. We're still working with a fork that's embedded into IdSvr (and thus internalized). The original pushback (as far as I remember and understand) from you was that you felt that any host using Autofac should be using a shared Autofac config and container. We feel differently because IdSvr is meant to be self-contained and encapsulates its work. Also, it doesn't help that OWIN itself doesn't define any standard DI.

This logical issue persists in ASP.NET 5, BTW: https://github.com/aspnet/DependencyInjection/issues/246

**Comment by tillig** [comment] 2015-11-04 15:32
Fair enough. The reason I thought it might be related was that, if you expose control of configuring nested containers like the one in Identity Server, some of the things may need to "leak out" to give access to folks to hook into. I can see a plugin developer wanting to get the request lifetime scope from a component used within Identity Server and having that context key available in some form so the right scope is grabbed would be important.

If it's not related, it's not related. No big deal.

Either way I'd love to hear of this is fixed so we can potentially close it.

**Comment by brockallen** [comment] 2015-11-04 15:39
I suspect we can close this. I do appreciate your time.

**Comment by tillig** [comment] 2015-11-04 15:54
No problem. Let me know if there's anything else we can do.

**Closed** 2015-11-04 15:53 UTC
Labels: enhancement
